resolver: lts-14.7
allow-newer: true

packages:
  - .

extra-deps:
  - stm-containers-1.0.1
  - hashable-1.2.7.0
  - stm-2.5.0.0
  - text-1.2.3.1
  - hashtables-1.2.4.1
  - containers-0.6.0.1
  - async-2.2.2
